CREATE TABLE TMQ_TIPO_DOCUMENTO(
	DNI_ID SERIAL,
	DS_NOMBRE VARCHAR(60),
	PRIMARY KEY (DNI_ID)
);


CREATE TABLE TMQ_PERSONA(
	DNI_ID SERIAL,
	NM_ID_TIPO_DOCUMENTO SMALLINT,
	DS_DOCUMENTO VARCHAR(12),
	FE_REGISTRO DATE,
	PRIMARY KEY (DNI_ID),
	FOREIGN KEY (NM_ID_TIPO_DOCUMENTO) REFERENCES TMQ_TIPO_DOCUMENTO(DNI_ID)
);

CREATE TABLE TMQ_CLIENTE(
	DNI_ID INTEGER,
	DS_CORREO VARCHAR(150),
	NM_TELEFONO INTEGER,
	DS_DIRECCION VARCHAR(150),
	PRIMARY KEY (DNI_ID),
	FOREIGN KEY (DNI_ID) REFERENCES TMQ_PERSONA(DNI_ID)
);

CREATE TABLE TMQ_EMPLEADOS(
	DNI_ID INTEGER,
	DS_CARGO VARCHAR(150),
	FE_INGRESO DATE,
	FE_RETIRO DATE,
	PRIMARY KEY (DNI_ID),
	FOREIGN KEY (DNI_ID) REFERENCES TMQ_PERSONA(DNI_ID)
);

CREATE TABLE TMQ_INSUMOS(
	DNI_ID SERIAL,
	DS_NOMBRE VARCHAR(150),
	NM_VALOR INTEGER,
	NM_UNIDADES INTEGER,
	PRIMARY KEY (DNI_ID)
);

CREATE TABLE TMQ_SERVICIOS(
	DNI_ID SERIAL,
	DS_NOMBRE VARCHAR(150),
	DS_OBSERVACION VARCHAR(255),
	PRIMARY KEY(DNI_ID)
);

CREATE TABLE TMQ_ENCABEZADO_SERVICIO(
	DNI_ID SERIAL,
	NM_ID_CLIENTE INTEGER,
	NM_VALOR_TOTAL BIGINT,
	NM_HORAS_TOTALES_LABORADAS INTEGER,
	FE_SERVICIO DATE,
	PRIMARY KEY(DNI_ID),
	FOREIGN KEY(NM_ID_CLIENTE) REFERENCES TMQ_CLIENTE(DNI_ID)
);

CREATE TABLE TMQ_DETALLE_SERVICIO(
	DNI_ID SERIAL,
	NM_ID_EMPLEADO INTEGER,
	NM_ID_SERVICIO INTEGER,
	NM_HORAS INTEGER,
	NM_VALOR_HORA INTEGER,
	DS_OBSERVACION VARCHAR(255),
	PRIMARY KEY (DNI_ID),
	FOREIGN KEY (DNI_ID) REFERENCES TMQ_EMPLEADOS(DNI_ID),
	FOREIGN KEY (DNI_ID) REFERENCES TMQ_SERVICIOS(DNI_ID)
);

CREATE TABLE TMQ_INSUMOS_DETALLE_SERVICIO(
	DNI_ID SERIAL,
	NM_ID_INSUMO INTEGER,
	NM_ID_DETALLE_SERVICIO INTEGER,
	PRIMARY KEY (DNI_ID) 
);